package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// Prometheus gauges for simulation metrics.
// These are updated from SimulationMetrics to expose to Prometheus.
var (
	// Operation metrics
	simOperationsTotal = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "simulation_operations_total",
		Help: "Total number of simulation operations executed",
	})
	simOperationsSucceeded = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "simulation_operations_succeeded",
		Help: "Number of successful simulation operations",
	})
	simOperationsFailed = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "simulation_operations_failed",
		Help: "Number of failed simulation operations",
	})
	simOperationsDelayed = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "simulation_operations_delayed",
		Help: "Number of delayed simulation operations",
	})

	// Transaction metrics
	simTransactionsGenerated = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "simulation_transactions_generated",
		Help: "Total number of transactions generated by simulation",
	})

	// User lifecycle metrics
	simUsersCreated = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "simulation_users_created",
		Help: "Total number of simulated users created",
	})
	simUsersKYCVerified = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "simulation_users_kyc_verified",
		Help: "Number of simulated users with verified KYC",
	})
	simUsersActivated = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "simulation_users_activated",
		Help: "Number of activated simulated users",
	})
	simActivePersonas = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "simulation_active_personas",
		Help: "Number of active persona types in simulation",
	})

	// Verification metrics
	simVerificationsCreated = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "simulation_verifications_created",
		Help: "Total verifications created by simulation",
	})
	simVerificationsAutoApproved = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "simulation_verifications_auto_approved",
		Help: "Number of auto-approved verifications",
	})

	// Timing metrics
	simAverageDelayMs = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "simulation_average_delay_ms",
		Help: "Average delay in milliseconds for simulation operations",
	})

	// Mode indicator (use labels for mode)
	simModeInfo = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "simulation_mode_info",
		Help: "Current simulation mode (1 for active mode)",
	}, []string{"mode"})
)

// UpdatePrometheusMetrics updates Prometheus gauges from SimulationMetrics snapshot.
// Call this method periodically or before each Prometheus scrape.
func (m *SimulationMetrics) UpdatePrometheusMetrics() {
	snapshot := m.GetSnapshot()

	// Operation metrics
	simOperationsTotal.Set(float64(snapshot.OperationsTotal))
	simOperationsSucceeded.Set(float64(snapshot.OperationsSucceeded))
	simOperationsFailed.Set(float64(snapshot.OperationsFailed))
	simOperationsDelayed.Set(float64(snapshot.OperationsDelayed))

	// Transaction metrics
	simTransactionsGenerated.Set(float64(snapshot.TransactionsGenerated))

	// User lifecycle metrics
	simUsersCreated.Set(float64(snapshot.UsersCreated))
	simUsersKYCVerified.Set(float64(snapshot.UsersKYCVerified))
	simUsersActivated.Set(float64(snapshot.UsersActivated))
	simActivePersonas.Set(float64(snapshot.ActivePersonas))

	// Verification metrics
	simVerificationsCreated.Set(float64(snapshot.VerificationsCreated))
	simVerificationsAutoApproved.Set(float64(snapshot.VerificationsAutoApproved))

	// Timing metrics
	simAverageDelayMs.Set(snapshot.AverageDelayMs)

	// Mode info - reset all modes then set current
	simModeInfo.Reset()
	if snapshot.CurrentMode != "" {
		simModeInfo.WithLabelValues(snapshot.CurrentMode).Set(1)
	}
}
